services:
  - type: web
    name: difa-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: true
      - key: REDIS_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: AT_USERNAME
        value: sandbox
      - key: AT_API_KEY
        sync: false
      - key: AT_SENDER_ID
        value: DIFA
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: GOOGLE_MAPS_API_KEY
        sync: false
